language: csharp

mono: none
dotnet: 2.2
dist: xenial

script:
  - dotnet test ./test/Camunda.Worker.Tests/Camunda.Worker.Tests.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover

after_script:
  - bash <(curl -s https://codecov.io/bash) -f ./test/Camunda.Worker.Tests/coverage.opencover.xml

notifications:
  email: false
